// src/app/components/Header/index.tsx
import React from 'react';
import {Link} from 'react-router-dom';

import GitHubIcon from '@material-ui/icons/GitHub';

import styles from './index.module.scss';

const Header = ({isInHome}) => {
    return (
        <header className={`${styles['header']} ${!isInHome ? styles['header--colorful'] : ''}`}>
            <div className={styles['header__logo']}>
                <Link className={styles['header__logo__link']} to="/">
                    CSS Animations
                </Link>
            </div>

            <div className={styles['header__github']}>
                <a
                    href="https://github.com/BijanProgrammer/css-animations"
                    target="_blank"
                    rel="noreferrer"
                    title="GitHub Page"
                >
                    <GitHubIcon className={styles['header__github__icon']} />
                </a>
            </div>
        </header>
    );
};

export default Header;

// src/app/components/header/header.component.ts
import {Component} from '@angular/core';
import {NavigationEnd, Router} from '@angular/router';

import {ThemeService} from '../../services/theme.service';

import {Theme} from 'src/app/models/theme';

@Component({
    selector: 'app-header',
    templateUrl: './header.component.html',
    styleUrls: ['./header.component.scss'],
})
export class HeaderComponent {
    public Theme = Theme;

    public isInHome: boolean = false;

    public constructor(private router: Router, public themeService: ThemeService) {
        router.events.subscribe((event) => {
            if (event instanceof NavigationEnd) this.isInHome = event.urlAfterRedirects === '/';
        });
    }
}

<header class="header" [ngClass]="{'header--colorful': !isInHome}">
    <div class="header__logo">
        <a class="header__logo__link" routerLink="/">CSS Animations</a>
    </div>

    <div class="header__github">
        <a
            href="https://github.com/BijanProgrammer/css-animations"
            target="_blank"
            rel="noreferrer"
            title="GitHub Page"
        >
            <logo-github></logo-github>
        </a>
    </div>

    <div class="header__theme-toggle-button" (click)="themeService.toggleTheme()">
        <icon-dark-mode *ngIf="themeService.theme === Theme.LIGHT"></icon-dark-mode>
        <icon-light-mode *ngIf="themeService.theme === Theme.DARK"></icon-light-mode>
    </div>
</header>
